# Generated by Django 4.0.1 on 2022-01-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataschemecolumn',
            name='type',
            field=models.CharField(choices=[('Company', 'Company - Text'), ('Job', 'Job - Char'), ('Age', 'Age - Int')], default=None, max_length=30),
        ),
    ]
