# Generated by Django 4.0.1 on 2022-01-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_main', '0002_dataschemecolumn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschemecolumn',
            name='type',
            field=models.CharField(choices=[('Company', 'Company'), ('Job', 'Job'), ('Age', 'Age')], default=None, max_length=30),
        ),
    ]
