# Generated by Django 4.0.1 on 2022-01-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_main', '0003_alter_dataschemecolumn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschemecolumn',
            name='type',
            field=models.IntegerField(),
        ),
    ]
