# Generated by Django 4.0.1 on 2022-01-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_main', '0005_remove_dataschemecolumn_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataschemecolumn',
            name='parent_scheme',
        ),
    ]
