# Generated by Django 4.0.1 on 2022-01-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_main', '0006_remove_dataschemecolumn_parent_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataschemecolumn',
            name='parent_scheme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='csv_main.datascheme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataschemecolumn',
            name='type',
            field=models.CharField(choices=[('Company', 'Company'), ('Job', 'Job'), ('Age', 'Age')], default=None, max_length=30),
        ),
    ]
