# Generated by Django 4.0.1 on 2022-01-20 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_main', '0007_dataschemecolumn_parent_scheme_dataschemecolumn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataschemecolumn',
            name='order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
