# Generated by Django 4.0.1 on 2022-01-20 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_main', '0009_dataschemecolumn_int_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschemecolumn',
            name='int_range',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
