# Generated by Django 4.0.1 on 2022-01-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_main', '0010_alter_dataschemecolumn_int_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschemecolumn',
            name='type',
            field=models.CharField(choices=[('Company', 'Company'), ('Email', 'Email'), ('Job', 'Job'), ('Company name', 'Company name'), ('Text', 'Text')], default=None, max_length=30),
        ),
    ]
