# Generated by Django 4.0.1 on 2022-01-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_main', '0011_alter_dataschemecolumn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datascheme',
            name='file',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
