# Generated by Django 4.0.1 on 2022-01-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_main', '0012_datascheme_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschemecolumn',
            name='type',
            field=models.CharField(choices=[('Company', 'Company'), ('Email', 'Email'), ('Job', 'Job'), ('Phone Number', 'Phone Number'), ('Text', 'Text'), ('Boolean', 'Boolean'), ('Address', 'Address'), ('Link', 'Link'), ('Age', 'Age')], default=None, max_length=30),
        ),
    ]
